version: "3"
services:

  timesketch:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
      - postgres
      - redis
    environment:
      - POSTGRES_USER=timesketch
      - POSTGRES_PASSWORD=password
      - POSTGRES_ADDRESS=postgres
      - POSTGRES_PORT=5432
      - ELASTIC_ADDRESS=elasticsearch
      - ELASTIC_PORT=9200
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
      - NEO4J_ADDRESS=neo4j
      - NEO4J_PORT=7474
    volumes:
      - timelines:/timelines
    restart: always

  worker:
    build: .
    command: worker
    depends_on:
      - elasticsearch
      - postgres
      - redis
    environment:
      - POSTGRES_USER=timesketch
      - POSTGRES_PASSWORD=password
      - POSTGRES_ADDRESS=postgres
      - POSTGRES_PORT=5432
      - ELASTIC_ADDRESS=elasticsearch
      - ELASTIC_PORT=9200
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
    volumes:
      - timelines:/timelines
    restart: always

  elasticsearch:
    image: elasticsearch:5-alpine
    volumes:
      - ./contrib:/usr/share/elasticsearch/config/scripts
      - ./esdata:/usr/share/elasticsearch/data
    restart: always

  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=timesketch
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    restart: always

  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=none
    restart: always

volumes:
  timelines:
